---

- name: Copy Filebeat package
  ansible.builtin.copy:
    src: filebeat-8.12.2-x86_64.rpm
    dest: /tmp/filebeat-8.12.2-x86_64.rpm

- name: Install filebeat
  ansible.builtin.yum:
    name: /tmp/filebeat-8.12.2-x86_64.rpm
    state: present

- name: Configure Filebeat
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Start filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: true